# Generated by Django 4.2.23 on 2026-01-07 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientdoc', '0019_bulkinvoiceupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmationdocument',
            name='uploaded_dc',
            field=models.FileField(blank=True, null=True, upload_to='confirmation_docs/dc/', verbose_name='Custom DC PDF'),
        ),
        migrations.AddField(
            model_name='confirmationdocument',
            name='uploaded_invoice',
            field=models.FileField(blank=True, null=True, upload_to='confirmation_docs/inv/', verbose_name='Custom Invoice PDF'),
        ),
    ]
