# Generated by Django 4.2.23 on 2026-01-07 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientdoc', '0020_confirmationdocument_uploaded_dc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Item Description (Snapshot)'),
        ),
    ]
